// client/src/components/ai/AIToolCard.jsx
import React from 'react';
import { Link } from 'react-router-dom';

const AIToolCard = ({ tool }) => {
    const { id, title, description, icon, path, color } = tool;

    return (
        <Link to={path} className="ai-tool-card" style={{ backgroundColor: color }}>
            <div className="tool-icon">
                <i className={icon}></i>
            </div>
            <div className="tool-info">
                <h3 className="tool-title">{title}</h3>
                <p className="tool-description">{description}</p>
            </div>
        </Link>
    );
};

export default AIToolCard;

// client/src/components/ai/AIToolCard.vue
<template>
  <router-link :to="tool.path" class="ai-tool-card" :style="{ backgroundColor: tool.color }">
    <div class="tool-icon">
      <i :class="tool.icon"></i>
    </div>
    <div class="tool-info">
      <h3 class="tool-title">{{ tool.title }}</h3>
      <p class="tool-description">{{ tool.description }}</p>
    </div>
  </router-link>
</template>

<script>
export default {
  name: 'AIToolCard',
  props: {
    tool: {
      type: Object,
      required: true
    }
  }
}
</script>
