// client/src/views/student/ConsultationFeedback.vue
<template>
    <div class="consultation-feedback-page">
        <div class="feedback-header">
            <h1>启明隅在线咨询 - 评价反馈</h1>
            <p>您的反馈将帮助我们提供更好的服务</p>
        </div>

        <div v-if="loading" class="loading-state">
            <i class="fas fa-spinner fa-spin"></i>
            <p>加载中...</p>
        </div>

        <div v-else-if="error" class="feedback-error">
            <i class="fas fa-exclamation-circle"></i>
            <span>{{ error }}</span>
            <router-link to="/student/consultations" class="back-button">
                返回咨询列表
            </router-link>
        </div>

        <div v-else class="feedback-content">
            <div class="consultant-info">
                <img :src="consultation.teacher.avatar || '/images/default-avatar.jpg'" :alt="consultation.teacher.name"
                    class="teacher-avatar" />
                <div class="teacher-details">
                    <h3>{{ consultation.teacher.name }}</h3>
                    <p>{{ consultation.subject }} 教师</p>
                </div>
            </div>

            <div class="feedback-form-container">
                <div class="feedback-form-header">
                    <h2>为{{ consultation.teacher.name }}老师的咨询服务评分</h2>
                    <p>请根据此次咨询体验进行评价</p>
                </div>

                <div v-if="submitError" class="error-message">
                    <i class="fas fa-exclamation-circle"></i>
                    <span>{{ submitError }}</span>
                </div>

                <form @submit.prevent="handleSubmit" class="feedback-form">
                    <div class="rating-section">
                        <label>服务满意度</label>
                        <div class="star-rating">
                            <button v-for="n in 5" :key="n" type="button"
                                :class="['star-btn', n <= feedback.rating ? 'active' : '']"
                                @click="feedback.rating = n">
                                <i class="fas fa-star"></i>
                            </button>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="comment">评价内容</label>
                        <textarea id="comment" v-model="feedback.comment" rows="5"
                            placeholder="请分享您对此次咨询的评价和建议..."></textarea>
                    </div>

                    <button type="submit" class="submit-btn" :disabled="submitting || !feedback.rating">
                        <template v-if="submitting">
                            <i class="fas fa-spinner fa-spin"></i> 提交中...
                        </template>
                        <template v-else>
                            <i class="fas fa-paper-plane"></i> 提交评价
                        </template>
                    </button>
                </form>
            </div>
        </div>
    </div>
</template>

<script>
import { ref, reactive, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { getConsultationById, submitFeedback } from '../../services/consultationService'

export default {
    name: 'ConsultationFeedback',
    setup() {
        const route = useRoute()
        const router = useRouter()
        const { id } = route.params

        const consultation = ref(null)
        const loading = ref(true)
        const error = ref('')
        const submitting = ref(false)
        const submitError = ref('')

        const feedback = reactive({
            rating: 0,
            comment: ''
        })

        // 加载咨询详情
        onMounted(async () => {
            try {
                loading.value = true
                error.value = ''

                const data = await getConsultationById(id)

                if (data.status !== 'completed') {
                    error.value = '只能对已完成的咨询进行评价'
                    loading.value = false
                    return
                }

                consultation.value = data
                loading.value = false
            } catch (err) {
                error.value = err.message || '加载咨询详情失败'
                loading.value = false
                console.error('加载咨询详情错误:', err)
            }
        })

        // 提交评价
        const handleSubmit = async () => {
            try {
                if (!feedback.rating) {
                    submitError.value = '请选择满意度评分'
                    return
                }

                submitting.value = true
                submitError.value = ''

                await submitFeedback(id, feedback)

                // 提交成功后跳转
                router.push({
                    path: '/student/consultations',
                    query: { feedbackSuccess: 'true' }
                })
            } catch (err) {
                submitError.value = err.message || '提交评价失败，请重试'
                submitting.value = false
                console.error('提交评价错误:', err)
            }
        }

        return {
            consultation,
            loading,
            error,
            submitting,
            submitError,
            feedback,
            handleSubmit
        }
    }
}
</script>

// client/src/pages/student/ConsultationFeedback.jsx
import React, { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { getConsultationById, submitConsultationFeedback } from '../../services/consultationService';

const ConsultationFeedback = () => {
    const { id } = useParams();
    const navigate = useNavigate();

    const [consultation, setConsultation] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    const [feedback, setFeedback] = useState({
        rating: 5,
        comment: ''
    });

    const [submitting, setSubmitting] = useState(false);
    const [submitError, setSubmitError] = useState('');

    // 加载咨询详情
    useEffect(() => {
        const fetchConsultationDetail = async () => {
            try {
                setLoading(true);
                const consultationData = await getConsultationById(id);
                setConsultation(consultationData);

                // 如果咨询不是已完成状态或已有反馈，重定向回详情页
                if (consultationData.status !== 'completed' || consultationData.feedback) {
                    navigate(`/student/consultation/detail/${id}`);
                    return;
                }

                setLoading(false);
            } catch (error) {
                setError(error.message || '加载咨询详情失败');
                setLoading(false);
                console.error('加载咨询详情错误:', error);
            }
        };

        fetchConsultationDetail();
    }, [id, navigate]);

    // 处理评分变化
    const handleRatingChange = (newRating) => {
        setFeedback({
            ...feedback,
            rating: newRating
        });
    };

    // 处理评论变化
    const handleCommentChange = (e) => {
        setFeedback({
            ...feedback,
            comment: e.target.value
        });
    };

    // 提交反馈
    const handleSubmit = async (e) => {
        e.preventDefault();

        try {
            setSubmitting(true);
            setSubmitError('');

            await submitConsultationFeedback(id, feedback);

            // 提交成功后重定向回详情页
            navigate(`/student/consultation/detail/${id}`);
        } catch (error) {
            setSubmitError(error.message || '提交反馈失败');
            setSubmitting(false);
            console.error('提交反馈错误:', error);
        }
    };

    if (loading) {
        return (
            <div className="feedback-loading">
                <i className="fas fa-spinner fa-spin"></i>
                <span>加载中...</span>
            </div>
        );
    }

    if (error) {
        return (
            <div className="feedback-error">
                <i className="fas fa-exclamation-circle"></i>
                <span>{error}</span>
                <Link to="/student/consultations" className="back-button">
                    返回咨询列表
                </Link>
            </div>
        );
    }

    return (
        <div className="feedback-page">
            <div className="page-header">
                <div className="header-left">
                    <Link to={`/student/consultation/detail/${id}`} className="back-link">
                        <i className="fas fa-arrow-left"></i> 返回详情
                    </Link>
                    <h1>咨询评价</h1>
                </div>
            </div>

            <div className="feedback-content">
                <div className="consultation-summary">
                    <h2>咨询信息</h2>
                    <div className="summary-info">
                        <div className="info-item">
                            <span className="info-label">教师:</span>
                            <div className="teacher-info">
                                <img
                                    src={consultation.teacher.avatar || '/images/default-avatar.jpg'}
                                    alt={consultation.teacher.name}
                                    className="teacher-avatar"
                                />
                                <span className="teacher-name">{consultation.teacher.name}</span>
                            </div>
                        </div>

                        <div className="info-item">
                            <span className="info-label">学科:</span>
                            <span className="info-value">{consultation.subject}</span>
                        </div>
                    </div>
                </div>

                <div className="feedback-form-container">
                    <div className="feedback-header">
                        <h1>启明隅在线咨询 - 评价反馈</h1>
                        <p>您的反馈将帮助我们提供更好的服务</p>
                    </div>

                    <div className="feedback-form-header">
                        <h2>为{consultation.teacher.name}老师的咨询服务评分</h2>
                        <p>请根据此次咨询体验进行评价</p>
                    </div>

                    {submitError && (
                        <div className="submit-error">
                            <i className="fas fa-exclamation-circle"></i> {submitError}
                        </div>
                    )}

                    <form onSubmit={handleSubmit} className="feedback-form">
                        <div className="form-group">
                            <label>教师表现评分</label>
                            <div className="rating-input">
                                {[1, 2, 3, 4, 5].map((star) => (
                                    <i
                                        key={star}
                                        className={`fas fa-star ${star <= feedback.rating ? 'active' : ''}`}
                                        onClick={() => handleRatingChange(star)}
                                    ></i>
                                ))}
                                <span className="rating-value">{feedback.rating}/5</span>
                            </div>
                        </div>

                        <div className="form-group">
                            <label>评价内容 (可选)</label>
                            <textarea
                                value={feedback.comment}
                                onChange={handleCommentChange}
                                placeholder="请分享您对本次咨询的评价和建议..."
                                rows={5}
                            ></textarea>
                        </div>

                        <button
                            type="submit"
                            className="submit-button"
                            disabled={submitting}
                        >
                            {submitting ? (
                                <>
                                    <i className="fas fa-spinner fa-spin"></i> 提交中...
                                </>
                            ) : (
                                <>
                                    <i className="fas fa-paper-plane"></i> 提交评价
                                </>
                            )}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    );
};

export default ConsultationFeedback;
