// client/src/views/student/ConsultationRoom.vue
<template>
    <div class="consultation-room">
        <div v-if="loading" class="loading-state">
            <i class="fas fa-spinner fa-spin"></i>
            <p>正在进入咨询室...</p>
        </div>

        <div v-else-if="error" class="error-state">
            <i class="fas fa-exclamation-circle"></i>
            <p>{{ error }}</p>
            <router-link to="/student/consultations" class="back-button">
                返回咨询列表
            </router-link>
        </div>

        <template v-else>
            <div class="room-header">
                <div class="header-left">
                    <router-link :to="`/student/consultation/detail/${id}`" class="back-link">
                        <i class="fas fa-arrow-left"></i> 返回咨询详情
                    </router-link>
                    <h1>启明隅在线咨询室</h1>
                </div>
                <div class="header-right">
                    <div class="teacher-info">
                        <img :src="consultation.teacher.avatar || '/images/default-avatar.jpg'"
                            :alt="consultation.teacher.name" class="teacher-avatar" />
                        <div class="teacher-name">{{ consultation.teacher.name }} 老师</div>
                    </div>
                </div>
            </div>

            <div class="messages-container" ref="messagesContainer">
                <div v-if="messages.length === 0" class="empty-messages">
                    <i class="fas fa-comments"></i>
                    <p>咨询已开始，请发送消息</p>
                </div>

                <template v-else>
                    <div v-for="(msg, index) in messages" :key="index"
                        :class="['message', msg.sender === currentUser._id ? 'outgoing' : 'incoming']">
                        <div class="message-content">
                            <div class="message-text">{{ msg.content }}</div>
                            <div class="message-time">{{ formatTime(msg.createdAt) }}</div>
                            <div v-if="msg.read && msg.sender === currentUser._id" class="message-status">
                                <i class="fas fa-check"></i> 已读
                            </div>
                        </div>
                    </div>
                </template>

                <div ref="messagesEnd"></div>
            </div>

            <div class="message-input-container">
                <form @submit.prevent="handleSendMessage" class="message-form">
                    <textarea v-model="newMessage" placeholder="输入消息..." ref="messageInput" class="message-textarea"
                        :disabled="sending" @keydown="handleKeyDown"></textarea>

                    <button type="submit" class="send-button" :disabled="sending || !newMessage.trim()">
                        <i v-if="sending" class="fas fa-spinner fa-spin"></i>
                        <i v-else class="fas fa-paper-plane"></i>
                        发送
                    </button>
                </form>

                <div class="input-tips">
                    按Enter键发送，Shift+Enter换行
                </div>
            </div>
        </template>
    </div>
</template>

<script>
import { ref, onMounted, onUnmounted, nextTick } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { format } from 'date-fns'
import { getConsultationById } from '../../services/consultationService'
import { getCurrentUser } from '../../services/authService'
import {
    initSocket,
    joinConsultation,
    sendMessage,
    onNewMessage,
    markMessagesAsRead,
    onMessagesRead,
    onConsultationEnded
} from '../../services/socketService'

export default {
    name: 'ConsultationRoom',
    setup() {
        const route = useRoute()
        // eslint-disable-next-line no-unused-vars
        const router = useRouter()
        const { id } = route.params

        const consultation = ref(null)
        const messages = ref([])
        const loading = ref(true)
        const error = ref('')
        const newMessage = ref('')
        const sending = ref(false)
        const messagesContainer = ref(null)
        const messagesEnd = ref(null)
        const messageInput = ref(null)

        const currentUser = getCurrentUser()
        let socket = null

        // 滚动到最新消息
        const scrollToBottom = () => {
            nextTick(() => {
                if (messagesEnd.value) {
                    messagesEnd.value.scrollIntoView({ behavior: 'smooth' })
                }
            })
        }

        // 格式化消息时间
        const formatTime = (dateString) => {
            return format(new Date(dateString), 'HH:mm')
        }

        // 处理发送消息
        const handleSendMessage = async () => {
            if (!newMessage.value.trim() || sending.value) return

            try {
                sending.value = true

                // 发送消息
                const sentMessage = await sendMessage(consultation.value._id, newMessage.value)

                // 添加到本地消息列表
                messages.value.push(sentMessage)

                // 清空输入框并滚动到底部
                newMessage.value = ''
                scrollToBottom()

                sending.value = false

                // 聚焦输入框
                nextTick(() => {
                    if (messageInput.value) {
                        messageInput.value.focus()
                    }
                })
            } catch (err) {
                error.value = '发送消息失败，请重试'
                sending.value = false
                console.error('发送消息错误:', err)
            }
        }

        // 处理键盘事件
        const handleKeyDown = (e) => {
            // Enter发送，Shift+Enter换行
            if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault()
                handleSendMessage()
            }
        }

        // 初始化咨询室
        onMounted(async () => {
            try {
                loading.value = true

                // 获取咨询详情
                const data = await getConsultationById(id)
                consultation.value = data

                // 检查咨询状态
                if (data.status !== 'accepted' && data.status !== 'completed') {
                    error.value = '咨询尚未开始或已结束'
                    loading.value = false
                    return
                }

                // 初始化Socket连接
                socket = initSocket()

                // 加入咨询房间
                const roomData = await joinConsultation(id)
                messages.value = roomData.messages || []

                // 监听新消息
                onNewMessage((newMsg) => {
                    messages.value.push(newMsg)
                    scrollToBottom()

                    // 如果不是自己发的消息，标记为已读
                    if (newMsg.sender !== currentUser._id) {
                        markMessagesAsRead(id)
                    }
                })

                // 监听消息已读状态
                onMessagesRead((data) => {
                    if (data.consultationId === id) {
                        // 更新消息已读状态
                        messages.value = messages.value.map(msg =>
                            msg.sender === currentUser._id ? { ...msg, read: true } : msg
                        )
                    }
                })

                // 监听咨询结束
                onConsultationEnded((data) => {
                    if (data.consultationId === id) {
                        // 显示咨询结束提示
                        alert('咨询已结束')
                        // 刷新咨询状态
                        consultation.value = { ...consultation.value, status: 'completed' }
                    }
                })

                // 标记消息为已读
                if (messages.value.some(msg => msg.sender !== currentUser._id && !msg.read)) {
                    markMessagesAsRead(id)
                }

                loading.value = false
                scrollToBottom()

                // 聚焦输入框
                nextTick(() => {
                    if (messageInput.value) {
                        messageInput.value.focus()
                    }
                })
            } catch (err) {
                error.value = err.message || '加载咨询室失败'
                loading.value = false
                console.error('加载咨询室错误:', err)
            }
        })

        // 组件销毁时清理
        onUnmounted(() => {
            // 清理任何监听器
            if (socket) {
                socket.off('newMessage')
                socket.off('messagesRead')
                socket.off('consultationEnded')
            }
        })

        return {
            id,
            consultation,
            messages,
            loading,
            error,
            newMessage,
            sending,
            currentUser,
            messagesContainer,
            messagesEnd,
            messageInput,
            formatTime,
            handleSendMessage,
            handleKeyDown
        }
    }
}
</script>

// client/src/pages/student/ConsultationRoom.jsx
import React, { useState, useEffect, useRef } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { getConsultationById } from '../../services/consultationService';
import {
    initSocket,
    joinConsultation,
    sendMessage,
    onNewMessage,
    markMessagesAsRead,
    onMessagesRead,
    onConsultationEnded
} from '../../services/socketService';
import { getCurrentUser } from '../../services/authService';

const ConsultationRoom = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const currentUser = getCurrentUser();
    const messageListRef = useRef(null);
    const messageInputRef = useRef(null);

    const [consultation, setConsultation] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [messages, setMessages] = useState([]);
    const [newMessage, setNewMessage] = useState('');
    const [sending, setSending] = useState(false);

    // 加载咨询详情和消息记录
    useEffect(() => {
        const fetchConsultation = async () => {
            try {
                setLoading(true);
                const data = await getConsultationById(id);

                // 验证咨询状态
                if (data.status !== 'accepted') {
                    navigate(`/student/consultation/detail/${id}`);
                    return;
                }

                // 验证当前用户是否是咨询的学生
                if (data.student._id !== currentUser.id) {
                    navigate('/student/consultations');
                    return;
                }

                setConsultation(data);
                setMessages(data.messages || []);
                setLoading(false);

                // 初始化WebSocket连接
                const socket = initSocket();

                // 加入咨询房间
                joinConsultation(id);

                // 标记消息为已读
                if (data.messages && data.messages.length > 0) {
                    const unreadIds = data.messages
                        .filter(msg => !msg.read && msg.sender._id !== currentUser.id)
                        .map(msg => msg._id);

                    if (unreadIds.length > 0) {
                        markMessagesAsRead(id, unreadIds);
                    }
                }
            } catch (error) {
                setError(error.message || '加载咨询详情失败');
                setLoading(false);
                console.error('加载咨询详情错误:', error);
            }
        };

        fetchConsultation();
    }, [id, currentUser.id, navigate]);

    // 监听WebSocket事件
    useEffect(() => {
        // 新消息事件
        onNewMessage((data) => {
            if (data.consultationId === id) {
                // 添加新消息到列表
                setMessages(prev => [...prev, data.message]);

                // 如果不是自己发送的消息，则标记为已读
                if (data.message.sender._id !== currentUser.id) {
                    markMessagesAsRead(id, [data.message._id]);
                }
            }
        });

        // 消息已读事件
        onMessagesRead((data) => {
            if (data.consultationId === id) {
                // 更新消息的已读状态
                setMessages(prev =>
                    prev.map(msg =>
                        data.messageIds.includes(msg._id)
                            ? { ...msg, read: true }
                            : msg
                    )
                );
            }
        });

        // 咨询结束事件
        onConsultationEnded((data) => {
            if (data.consultation._id === id) {
                alert('教师已结束本次咨询。');
                navigate(`/student/consultation/detail/${id}`);
            }
        });

        // 消息滚动到底部
        if (messageListRef.current) {
            messageListRef.current.scrollTop = messageListRef.current.scrollHeight;
        }

        // 清理函数
        return () => {
            const socket = initSocket();
            if (socket) {
                socket.off('consultation:message');
                socket.off('consultation:read');
                socket.off('consultation:ended');
            }
        };
    }, [id, currentUser.id, navigate, messages]);

    // 发送消息
    const handleSendMessage = async (e) => {
        e.preventDefault();

        if (!newMessage.trim()) return;

        try {
            setSending(true);

            // 通过WebSocket发送消息
            sendMessage(id, newMessage.trim());

            // 清空输入框
            setNewMessage('');
            setSending(false);

            // 聚焦输入框
            if (messageInputRef.current) {
                messageInputRef.current.focus();
            }
        } catch (error) {
            console.error('发送消息错误:', error);
            setSending(false);
        }
    };

    // 格式化消息时间
    const formatMessageTime = (dateString) => {
        const date = new Date(dateString);
        return date.toLocaleString('zh-CN', {
            month: 'numeric',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        });
    };

    if (loading) {
        return (
            <div className="consultation-room-loading">
                <i className="fas fa-spinner fa-spin"></i>
                <span>正在进入咨询室...</span>
            </div>
        );
    }

    if (error) {
        return (
            <div className="consultation-room-error">
                <i className="fas fa-exclamation-circle"></i>
                <span>{error}</span>
                <Link to="/student/consultations" className="back-button">
                    返回咨询列表
                </Link>
            </div>
        );
    }

    return (
        <div className="consultation-room">
            <div className="room-header">
                <div className="header-left">
                    <Link to={`/student/consultation/detail/${id}`} className="back-link">
                        <i className="fas fa-arrow-left"></i> 返回咨询详情
                    </Link>
                    <h1>启明隅在线咨询室</h1>
                </div>
                <div className="header-right">
                    <div className="teacher-info">
                        <img
                            src={consultation.teacher.avatar || '/images/default-avatar.jpg'}
                            alt={consultation.teacher.name}
                            className="teacher-avatar"
                        />
                        <div className="teacher-name">{consultation.teacher.name} 老师</div>
                    </div>
                </div>
            </div>

            <div className="consultation-question">
                <h3>咨询问题:</h3>
                <p>{consultation.question}</p>
            </div>

            <div className="consultation-conversation">
                <div className="message-list" ref={messageListRef}>
                    {messages.length === 0 ? (
                        <div className="no-messages">
                            <i className="fas fa-comments"></i>
                            <p>还没有消息，开始发送消息向教师咨询吧</p>
                        </div>
                    ) : (
                        messages.map((message, index) => (
                            <div
                                key={message._id || index}
                                className={`message-item ${message.sender._id === currentUser.id ? 'sent' : 'received'}`}
                            >
                                <div className="message-avatar">
                                    <img
                                        src={message.sender.avatar || '/images/default-avatar.jpg'}
                                        alt={message.sender.name}
                                    />
                                </div>
                                <div className="message-content">
                                    <div className="message-header">
                                        <span className="message-sender">{message.sender.name}</span>
                                        <span className="message-time">{formatMessageTime(message.timestamp)}</span>
                                    </div>
                                    <div className="message-text">{message.content}</div>
                                    {message.sender._id === currentUser.id && (
                                        <div className="message-status">
                                            {message.read ? (
                                                <span className="read-status">已读</span>
                                            ) : (
                                                <span className="unread-status">未读</span>
                                            )}
                                        </div>
                                    )}
                                </div>
                            </div>
                        ))
                    )}
                </div>

                <form className="message-input-form" onSubmit={handleSendMessage}>
                    <textarea
                        ref={messageInputRef}
                        value={newMessage}
                        onChange={(e) => setNewMessage(e.target.value)}
                        placeholder="输入您的问题或想法..."
                        className="message-input"
                        onKeyDown={(e) => {
                            if (e.key === 'Enter' && !e.shiftKey) {
                                e.preventDefault();
                                handleSendMessage(e);
                            }
                        }}
                    ></textarea>
                    <button
                        type="submit"
                        className="send-button"
                        disabled={sending || !newMessage.trim()}
                    >
                        {sending ? (
                            <i className="fas fa-spinner fa-spin"></i>
                        ) : (
                            <i className="fas fa-paper-plane"></i>
                        )}
                        发送
                    </button>
                </form>

                <div className="input-tips">
                    按Enter键发送，Shift+Enter换行
                </div>
            </div>
        </div>
    );
};

export default ConsultationRoom;
