// client/src/views/student/ConsultationList.vue
<template>
  <div class="consultation-list-page">
    <div class="consultation-list-header">
      <h1>启明隅在线咨询</h1>
      <p>与专业教师一对一交流，解决您的学习难题</p>
    </div>

    <div class="page-header">
      <h1>我的咨询</h1>
      <router-link to="/student/consultation/teachers" class="new-consultation-btn">
        <i class="fas fa-plus"></i> 新咨询
      </router-link>
    </div>

    <div class="consultations-container">
      <!-- 分类标签 -->
      <div class="consultation-tabs">
        <button v-for="tab in tabs" :key="tab.value" :class="['tab-button', activeTab === tab.value ? 'active' : '']"
          @click="activeTab = tab.value">
          {{ tab.label }}
        </button>
      </div>

      <div class="consultations-content">
        <div v-if="loading" class="loading-state">
          <i class="fas fa-spinner fa-spin"></i>
          <p>加载咨询列表中...</p>
        </div>
        <div v-else-if="error" class="error-state">
          <i class="fas fa-exclamation-circle"></i>
          <p>{{ error }}</p>
          <button @click="loadConsultations" class="retry-btn">
            <i class="fas fa-redo"></i> 重试
          </button>
        </div>
        <div v-else-if="consultations.length === 0" class="empty-consultations">
          <img src="/images/empty-consultation.svg" alt="暂无咨询" />
          <h3>您还没有发起过咨询</h3>
          <p>启明隅在线咨询让您与专业教师一对一交流</p>
          <router-link to="/student/consultation/teachers" class="new-consultation-btn">
            <i class="fas fa-plus-circle"></i> 寻找教师咨询
          </router-link>
        </div>
        <div v-else-if="filteredConsultations.length === 0" class="no-consultations">
          <i class="fas fa-comments"></i>
          <h3>暂无{{ activeTab !== 'all' ? `${getStatusText(activeTab)}的` : '' }}咨询记录</h3>
          <router-link to="/student/consultation/teachers" class="find-teacher-btn">
            寻找教师咨询
          </router-link>
        </div>
        <div v-else class="consultation-list">
          <div v-for="consultation in filteredConsultations" :key="consultation._id" class="consultation-card">
            <div class="card-header">
              <div class="teacher-info">
                <img :src="consultation.teacher.avatar || '/images/default-avatar.jpg'" :alt="consultation.teacher.name"
                  class="teacher-avatar" />
                <span class="teacher-name">{{ consultation.teacher.name }}</span>
              </div>
              <div :class="['status-badge', getStatusClass(consultation.status)]">
                {{ getStatusText(consultation.status) }}
              </div>
            </div>

            <div class="card-body">
              <div class="consultation-subject">
                <i class="fas fa-tag"></i>
                <span>{{ consultation.subject }}</span>
              </div>

              <div class="consultation-description">
                {{ consultation.description }}
              </div>

              <div class="consultation-time">
                <i class="far fa-clock"></i>
                <span>{{ formatDate(consultation.createdAt) }}</span>
              </div>
            </div>

            <div class="card-actions">
              <button v-if="consultation.status === 'pending'" @click="handleCancel(consultation._id)"
                class="cancel-btn">
                <i class="fas fa-times"></i> 取消咨询
              </button>

              <router-link v-if="consultation.status === 'accepted'"
                :to="`/student/consultation/room/${consultation._id}`" class="enter-room-btn">
                <i class="fas fa-door-open"></i> 进入咨询室
              </router-link>

              <router-link v-if="consultation.status === 'completed' && !consultation.studentReviewed"
                :to="`/student/consultation/completed/${consultation._id}`" class="new-request-btn">
                <i class="fas fa-redo"></i> 再次咨询
              </router-link>

              <router-link v-if="consultation.status === 'completed' && !consultation.feedback"
                :to="`/student/consultation/feedback/${consultation._id}`" class="feedback-btn">
                <i class="fas fa-star"></i> 评价咨询
              </router-link>

              <router-link :to="`/student/consultation/detail/${consultation._id}`" class="view-detail-btn">
                <i class="fas fa-eye"></i> 查看详情
              </router-link>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, computed, onMounted, reactive, watch } from 'vue'
import { getConsultations, cancelConsultation } from '../../services/consultationService'
import { initSocket, onConsultationStatus, onConsultationReady } from '../../services/socketService'
import { useRouter } from 'vue-router'

export default {
  name: 'ConsultationList',
  setup() {
    const router = useRouter()
    const consultations = ref([])
    const loading = ref(true)
    const error = ref('')
    const activeTab = ref('all')

    // 标签列表
    const tabs = [
      { label: '全部咨询', value: 'all' },
      { label: '待处理', value: 'pending' },
      { label: '已接受', value: 'accepted' },
      { label: '已完成', value: 'completed' },
      { label: '已取消/拒绝', value: 'canceled,rejected' }
    ]

    // 根据当前选中标签过滤咨询列表
    const filteredConsultations = computed(() => {
      if (activeTab.value === 'all') {
        return consultations.value
      }

      if (activeTab.value.includes(',')) {
        const statuses = activeTab.value.split(',')
        return consultations.value.filter(c => statuses.includes(c.status))
      }

      return consultations.value.filter(c => c.status === activeTab.value)
    })

    // 加载咨询列表
    const loadConsultations = async () => {
      try {
        loading.value = true
        error.value = ''
        const result = await getConsultations()
        consultations.value = result.data
        loading.value = false
      } catch (err) {
        error.value = '加载咨询列表失败'
        loading.value = false
        console.error('加载咨询列表错误:', err)
      }
    }

    // 取消咨询
    const handleCancel = async (id) => {
      if (!confirm('确定要取消这个咨询请求吗？')) {
        return
      }

      try {
        await cancelConsultation(id)
        // 更新列表中的咨询状态
        consultations.value = consultations.value.map(c =>
          c._id === id ? { ...c, status: 'canceled' } : c
        )
      } catch (err) {
        alert(`取消咨询失败: ${err.message}`)
        console.error('取消咨询错误:', err)
      }
    }

    // 格式化日期
    const formatDate = (dateString) => {
      const date = new Date(dateString)
      return date.toLocaleString('zh-CN', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })
    }

    // 获取状态文本
    const getStatusText = (status) => {
      switch (status) {
        case 'pending': return '待处理'
        case 'accepted': return '已接受'
        case 'rejected': return '已拒绝'
        case 'completed': return '已完成'
        case 'canceled': return '已取消'
        default: return status
      }
    }

    // 获取状态样式类名
    const getStatusClass = (status) => {
      switch (status) {
        case 'pending': return 'status-pending'
        case 'accepted': return 'status-accepted'
        case 'rejected': return 'status-rejected'
        case 'completed': return 'status-completed'
        case 'canceled': return 'status-canceled'
        default: return ''
      }
    }

    // 初始化WebSocket和加载数据
    onMounted(() => {
      // 初始化Socket
      const socket = initSocket()

      // 监听咨询状态变更
      onConsultationStatus((updatedConsultation) => {
        consultations.value = consultations.value.map(c =>
          c._id === updatedConsultation._id ? updatedConsultation : c
        )
      })

      // 监听咨询准备就绪事件
      onConsultationReady((consultationId) => {
        // 更新状态
        consultations.value = consultations.value.map(c =>
          c._id === consultationId ? { ...c, status: 'accepted' } : c
        )

        // 显示通知
        const notification = new Notification('咨询已准备就绪', {
          body: '您的咨询请求已被接受，点击进入咨询室',
          icon: '/logo.png'
        })

        notification.onclick = () => {
          window.focus()
          router.push(`/student/consultation/room/${consultationId}`)
        }
      })

      // 加载咨询列表
      loadConsultations()

      // 请求通知权限
      if (Notification.permission !== 'granted' && Notification.permission !== 'denied') {
        Notification.requestPermission()
      }
    })

    return {
      consultations,
      loading,
      error,
      activeTab,
      tabs,
      filteredConsultations,
      handleCancel,
      loadConsultations,
      formatDate,
      getStatusText,
      getStatusClass
    }
  }
}
</script>

// client/src/pages/student/ConsultationList.jsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { getConsultations, cancelConsultation } from '../../services/consultationService';
import { initSocket, onConsultationStatus, onConsultationReady } from '../../services/socketService';

const ConsultationList = () => {
    const navigate = useNavigate();

    const [consultations, setConsultations] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [activeTab, setActiveTab] = useState('all');

    // 加载咨询列表
    const loadConsultations = async () => {
        try {
            setLoading(true);
            const result = await getConsultations();
            setConsultations(result.data);
            setLoading(false);
        } catch (error) {
            setError('加载咨询列表失败');
            setLoading(false);
            console.error('加载咨询列表错误:', error);
        }
    };

    // 初始化WebSocket和加载数据
    useEffect(() => {
        // 初始化Socket
        const socket = initSocket();

        // 监听咨询状态变更
        onConsultationStatus((data) => {
            // 更新咨询状态
            setConsultations(prev =>
                prev.map(c =>
                    c._id === data.consultation._id
                        ? { ...c, status: data.consultation.status }
                        : c
                )
            );
        });

        // 监听咨询准备就绪
        onConsultationReady((data) => {
            // 提示用户可以进入咨询室
            const notification = `教师已接受您的咨询请求，可以开始咨询了！`;
            alert(notification);

            // 更新咨询状态
            setConsultations(prev =>
                prev.map(c =>
                    c._id === data.consultation._id
                        ? { ...c, status: data.consultation.status }
                        : c
                )
            );
        });

        // 加载咨询列表
        loadConsultations();

        // 清理函数
        return () => {
            // 移除WebSocket监听器
            if (socket) {
                socket.off('consultation:status');
                socket.off('consultation:ready');
            }
        };
    }, []);

    // 取消咨询请求
    const handleCancel = async (consultationId) => {
        if (!window.confirm('确定要取消这个咨询请求吗？')) {
            return;
        }

        try {
            await cancelConsultation(consultationId);

            // 更新状态
            setConsultations(prev =>
                prev.map(c =>
                    c._id === consultationId
                        ? { ...c, status: 'canceled' }
                        : c
                )
            );
        } catch (error) {
            alert(`取消失败: ${error.message}`);
            console.error('取消咨询错误:', error);
        }
    };

    // 进入咨询室
    const enterConsultation = (consultationId) => {
        navigate(`/student/consultation/room/${consultationId}`);
    };

    // 获取状态文本
    const getStatusText = (status) => {
        switch (status) {
            case 'pending': return '待处理';
            case 'accepted': return '已接受';
            case 'rejected': return '已拒绝';
            case 'completed': return '已完成';
            case 'canceled': return '已取消';
            default: return status;
        }
    };

    // 获取状态标志
    const getStatusBadge = (status) => {
        let badgeClass = '';

        switch (status) {
            case 'pending':
                badgeClass = 'badge-warning';
                break;
            case 'accepted':
                badgeClass = 'badge-success';
                break;
            case 'rejected':
                badgeClass = 'badge-danger';
                break;
            case 'completed':
                badgeClass = 'badge-info';
                break;
            case 'canceled':
                badgeClass = 'badge-secondary';
                break;
            default:
                badgeClass = 'badge-primary';
        }

        return (
            <span className={`status-badge ${badgeClass}`}>
                {getStatusText(status)}
            </span>
        );
    };

    // 格式化日期
    const formatDate = (dateString) => {
        const date = new Date(dateString);
        return date.toLocaleString('zh-CN', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        });
    };

    // 根据选中的标签筛选咨询
    const filteredConsultations = activeTab === 'all'
        ? consultations
        : consultations.filter(c => c.status === activeTab);

    return (
        <div className="consultation-list-page">
            <div className="consultation-list-header">
                <h1>启明隅在线咨询</h1>
                <p>与专业教师一对一交流，解决您的学习难题</p>
            </div>

            <div className="page-header">
                <h1>我的咨询</h1>
                <Link to="/student/consultation" className="new-consultation-btn">
                    <i className="fas fa-plus"></i> 新咨询
                </Link>
            </div>

            <div className="status-tabs">
                <button
                    className={activeTab === 'all' ? 'active' : ''}
                    onClick={() => setActiveTab('all')}
                >
                    全部
                </button>
                <button
                    className={activeTab === 'pending' ? 'active' : ''}
                    onClick={() => setActiveTab('pending')}
                >
                    待处理
                </button>
                <button
                    className={activeTab === 'accepted' ? 'active' : ''}
                    onClick={() => setActiveTab('accepted')}
                >
                    已接受
                </button>
                <button
                    className={activeTab === 'completed' ? 'active' : ''}
                    onClick={() => setActiveTab('completed')}
                >
                    已完成
                </button>
                <button
                    className={activeTab === 'rejected' ? 'active' : ''}
                    onClick={() => setActiveTab('rejected')}
                >
                    已拒绝
                </button>
                <button
                    className={activeTab === 'canceled' ? 'active' : ''}
                    onClick={() => setActiveTab('canceled')}
                >
                    已取消
                </button>
            </div>

            <div className="consultation-list-container">
                {loading ? (
                    <div className="loading">
                        <i className="fas fa-spinner fa-spin"></i>
                        <span>加载咨询列表中...</span>
                    </div>
                ) : error ? (
                    <div className="error">
                        <i className="fas fa-exclamation-circle"></i>
                        <span>{error}</span>
                        <button onClick={loadConsultations} className="retry-button">
                            重试
                        </button>
                    </div>
                ) : consultations.length === 0 ? (
                    <div className="empty-consultations">
                        <img src="/images/empty-consultation.svg" alt="暂无咨询" />
                        <h3>您还没有发起过咨询</h3>
                        <p>启明隅在线咨询让您与专业教师一对一交流</p>
                        <Link to="/student/consultation/teachers" className="new-consultation-btn">
                            <i className="fas fa-plus-circle"></i> 寻找教师咨询
                        </Link>
                    </div>
                ) : (
                    <div className="consultation-list">
                        {filteredConsultations.map(consultation => (
                            <div key={consultation._id} className="consultation-item">
                                <div className="consultation-header">
                                    <h3 className="consultation-subject">
                                        {consultation.subject}
                                    </h3>
                                    {getStatusBadge(consultation.status)}
                                </div>

                                <div className="consultation-teacher">
                                    <div className="teacher-info">
                                        <img
                                            src={consultation.teacher.avatar || '/images/default-avatar.jpg'}
                                            alt={consultation.teacher.name}
                                            className="teacher-avatar"
                                        />
                                        <span className="teacher-name">{consultation.teacher.name}</span>
                                    </div>

                                    <div className="consultation-meta">
                                        <div className="meta-item">
                                            <i className="fas fa-calendar"></i>
                                            <span>创建时间: {formatDate(consultation.createdAt)}</span>
                                        </div>

                                        {consultation.scheduledTime && (
                                            <div className="meta-item">
                                                <i className="fas fa-clock"></i>
                                                <span>预约时间: {formatDate(consultation.scheduledTime)}</span>
                                            </div>
                                        )}
                                    </div>
                                </div>

                                <div className="consultation-question">
                                    <h4>问题描述:</h4>
                                    <p>{consultation.question}</p>
                                </div>

                                <div className="consultation-actions">
                                    {consultation.status === 'pending' && (
                                        <button
                                            className="cancel-btn"
                                            onClick={() => handleCancel(consultation._id)}
                                        >
                                            <i className="fas fa-times"></i> 取消请求
                                        </button>
                                    )}

                                    {consultation.status === 'accepted' && (
                                        <button
                                            className="enter-btn"
                                            onClick={() => enterConsultation(consultation._id)}
                                        >
                                            <i className="fas fa-sign-in-alt"></i> 进入咨询
                                        </button>
                                    )}

                                    {consultation.status === 'rejected' && (
                                        <div className="rejection-reason">
                                            <i className="fas fa-info-circle"></i>
                                            <span>拒绝原因: {consultation.rejectionReason || '教师未提供拒绝原因'}</span>
                                        </div>
                                    )}

                                    {(consultation.status === 'completed' || consultation.status === 'rejected') && (
                                        <Link
                                            to={`/student/consultation/teacher/${consultation.teacher._id}`}
                                            className="new-request-btn"
                                        >
                                            <i className="fas fa-redo"></i> 再次咨询
                                        </Link>
                                    )}

                                    {consultation.status === 'completed' && !consultation.feedback && (
                                        <Link
                                            to={`/student/consultation/feedback/${consultation._id}`}
                                            className="feedback-btn"
                                        >
                                            <i className="fas fa-star"></i> 评价咨询
                                        </Link>
                                    )}

                                    <Link
                                        to={`/student/consultation/detail/${consultation._id}`}
                                        className="view-detail-btn"
                                    >
                                        <i className="fas fa-eye"></i> 查看详情
                                    </Link>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
};

export default ConsultationList;
